apiVersion: v1
kind: Service
metadata:
  name: finalproject
  namespace: finalproject
  labels:
    app: finalproject
spec:
  selector:
    app: finalproject
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 80
