apiVersion: apps/v1
kind: Deployment
metadata:
  name: finalproject
  labels:
    app: finalproject
  namespace: finalproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finalproject
  template:
    metadata:
      labels:
        app: finalproject
    spec:
      containers:
      - name: finalproject
        image: saaaaangho/ubuntu:apache2
